bday/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('club.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

club/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name="home"),
    path('blownCandle', views.blownCandle, name="blownCandle"),
    path('Gallery', views.Gallery, name="Gallery"),
    path('candle', views.candle, name="candle"),
    path('Message',views.Message,name = "Message"),
]

club/models.py
from django.db import models
import datetime

class GalleryImages(models.Model):
    EventName = models.TextField(max_length=200, default='all')
    EventDate = models.DateTimeField(default=datetime.datetime.today())


class Image(models.Model):
    gallery = models.ForeignKey(GalleryImages, on_delete=models.CASCADE)
    Image = models.ImageField(upload_to='static/images')


class GalleryHeadings(models.Model):
    heading = models.TextField(max_length=200)
    EventDate = models.DateTimeField(default=datetime.datetime.today())

club/views.py
from django.shortcuts import render
from .models import  GalleryImages, GalleryHeadings
import datetime
# Create your views here.

def  home(request):
    # sponsers = Sponsers.objects.all()
    # eventslist = EventsList.objects.all()
    # context = {'sponsers': sponsers, 'eventslist':eventslist}
    return render(request,'club/home.html')


def blownCandle(request):
    # eventslist = EventsList.objects.all()
    # context = {'eventslist':eventslist}
    return render(request,'club/blownCandle.html')


def Gallery(request):
    galleryimages = GalleryImages.objects.all().order_by('-EventDate')
    galleryheadings = GalleryHeadings.objects.all().order_by('-EventDate')
    context = {'galleryimages':galleryimages,'galleryheadings':galleryheadings}
    return render(request,'club/Gallery.html', context)

def Message(request):
    return render(request,'club/Message.html')

def  candle(request):
    # teammembers = TeamMembers.objects.all()
    # teamheadings = TeamHeadings.objects.all()
    # context = {'teammembers': teammembers, 'teamheadings':teamheadings}
    return render(request,'club/candle.html')

club/templates/club/Gallery.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <link rel="icon" href="/static/images/bg-home.jpg" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Gallery</title>
  <link rel="stylesheet" href="/static/styles/gallery.css" />
</head>
<body>
  <hr />
  <div id="gallery" class="container-fluid">
    {% for gallery in galleryimages %}
      {% for image in gallery.image_set.all %}
        <img style="border-radius: 1rem" src="{{ image.Image.url }}" alt="" onclick="openModal(this)" />
      {% endfor %}
    {% endfor %}
  </div>

  <div id="myModal" class="modal">
    <span class="close" onclick="closeModal()">&times;</span>
    <img class="modal-content" id="modalImage" />
  </div>
  <script src="/static/javascript/gallery.js"></script>
</body>
</html>

club/templates/club/Message.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Happy Birthday Sravanti!</title>
  <link rel="icon" href="/static/images/bg-home.jpg" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Cutive+Mono'><link rel="stylesheet" href="./style.css">
  <link rel="stylesheet" href="/static/styles/message.css">
</head>
<body>
<!-- partial:index.partial.html -->
<main>
 
 
  <audio id="musicMsg" src="/static/audio/bol4.mp3" loop="loop"></audio>
  <section class="mast">
    <div class="container">
      <h1 class="text">Saeng-il chuk-ha-he-yo Sravanti!</h1> 
      <p class="text">Happy Birthday !!!<br>
        My..
        Rakshasi , lil lady , pichi pilla , bangaramm , aunty <br>
        
My life got twisted upside down.<br> 
So I'd like to tell a story, just sit right there.<br>
And I'll tell you how I became the prince of Bel Air. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam magni illum facilis vero blanditiis doloremque beatae nam labore sapiente, autem, nesciunt deleniti necessitatibus rerum ullam eligendi dignissimos aut repudiandae. Eaque!</p>
      
<a href="/Gallery">
  <button id="galleryBtn">(⌐■_■)</button>
</a>
    </div>
  </section>
</main>
<!-- partial -->
  <script src='https://code.jquery.com/jquery-2.2.4.min.js'></script><script  src="./script.js"></script>
  <script src="/static/javascript/message.js"></script>
</body>

</html>

club/templates/club/blownCandle.html
<title>Happy Birthday Rakshasi!</title>
{% extends 'index.html' %}

{% block contents %}
  <main>
    <audio id="musicBD" src="/static/audio/happy.mp3" loop="loop"></audio>
    <div id="customAlert" class="alert">
      <div class="alert-content">
        <img id="bdayImage" src="/static/images/desktop-bg.png" class="bday_img" alt="">
        <br>
        <a href="Message">
          <button id="closeAlert">༼ つ ◕_◕ ༽つ</button>
        </a>
      </div>
    </div>
    <div id='stars1'></div>
    <div id='stars2'></div>
    <div id='stars3'></div>
    <div id="container">
      <div id="cake">
        <div id="flame">
          <div id="inner-flame"></div>
        </div>
        <div class="underline"></div>
      </div>
      <div id="countdown">
        <div id="cdDays">
          <div class="spacer"></div>
          <div id="daysNum"></div>
          <div class="label">DAY(S)</div>
        </div>
        <div id="cdHours">
          <div class="spacer"></div>
          <div id="hoursNum"></div>
          <div class="label">HOURS</div>
        </div>
        <div id="cdMins">
          <div class="spacer"></div>
          <div id="minsNum"></div>
          <div class="label">MINUTES</div>
        </div>
        <div id="cdSecs">
          <div class="spacer"></div>
          <div id="secsNum"></div>
          <div class="label">SECONDS</div>
        </div>
        <div id="text">UNTIL MY BIRTHDAY</div>
      </div>
    </div>
  </main>
  <script src="/static/javascript/test.js"></script>
  <script>
    // Update image source for mobile dimensions
    function updateImageSource() {
      var bdayImage = document.getElementById("bdayImage");
      var viewportWidth = window.innerWidth || document.documentElement.clientWidth;

      if (viewportWidth < 768) {
        bdayImage.src = "/static/images/mobile-poster.png"; // Replace with the mobile image source
      }
    }

    // Call the function initially and on window resize
    updateImageSource();
    window.addEventListener("resize", updateImageSource);
  </script>
{% endblock %}

club/templates/club/candle.html
{% extends 'index.html' %}

{% block contents %}

<main>
  <style>
    body {
      background-color: #1e1934 !important;
      background-image: none !important;
      color: white !important;
    }
  </style>
  <section class="candle">
    <h1>
      Make a wish..<br/>.. and blow out the candle</h1>
   <div class="glow" id="glow"></div>
   <div id="candle">
     <div class="stripe"></div>
     <div class="stripe"></div>
     <div class="stripe"></div>
     <div class="stripe"></div>
     <div class="stripe"></div>
     <div id="top">
       <div class="smoke"></div>
       <div class="smoke"></div>
       <div class="smoke"></div>
       <div id="knot"></div>
       <div class="burn" id="flame"></div>
     </div>
   </div>
   <!-- partial -->
     <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js'></script>
        
   <script src="/static/javascript/candle.js"></script>
  </section>
    
</main>

{% endblock %}

club/templates/club/home.html
{% extends 'index.html' %}

{% block contents %}
  <main>
    <div class="skip">
      <a href="/Gallery">
        <button class="skipBtn">▶</button>
      </a>
    </div>
    <div id='stars1'></div>
<div id='stars2'></div>
<div id='stars3'></div>
    <div id="container">
      
      <a href="candle" id="candleClick">
        <div id="cake">
          
          <div id="flame">
            <div id="inner-flame"></div>
          </div>
          <div class="underline"></div>
        </div>
      </a>
      <div id="countdown">
        <div id="cdDays">
          <div class="spacer"></div>
          <div id="daysNum"></div>
          <div class="label">DAY(S)</div>
        </div>
        <div id="cdHours">
          <div class="spacer"></div>
          <div id="hoursNum"></div>
          <div class="label">HOURS</div>
        </div>
        <div id="cdMins">
          <div class="spacer"></div>
          <div id="minsNum"></div>
          <div class="label">MINUTES</div>
        </div>
        <div id="cdSecs">
          <div class="spacer"></div>
          <div id="secsNum"></div>
          <div class="label">SECONDS</div>
        </div>
        <div id="text">UNTIL MY BIRTHDAY</div>
      </div>
    </div>
  </main>
  <script src="/static/javascript/home.js"></script>
{% endblock %}

templates/index.html
{% load static %}
{% url 'home' as home %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="/static/images/bg-home.jpg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bday</title>

    <!-- CSS -->
    
    <link rel="stylesheet" href="{% static 'styles/index.css' %}">
    <link rel="stylesheet" href="{% static 'styles/home.css' %}">
    <link rel="stylesheet" href="{% static 'styles/candle.css' %}">
    <!-- ekdjhwyidwkbdek -->


    <!-- Javascript -->
    <script src="{% static 'javascript/index.js' %}"></script>


    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>

</head>
<body>

{% block contents %}
{% endblock %}

    
    
</body>
</html>